// Package relay implements the bellbird relay server.
// It is designed to be imported as a library; the CLI in cmd/bellbird is a thin wrapper.
//
// Usage:
//
//	cfg := relay.Config{
//	    ListenAddr: ":9999",
//	    PrivateKey: privKeyBytes,
//	}
//	r, err := relay.New(cfg)
//	if err != nil { log.Fatal(err) }
//	log.Fatal(r.Start(context.Background()))
package relay

import (
	"context"
	"crypto/sha256"
	"crypto/subtle"
	"errors"
	"fmt"
	"log"
	"net"
	"strconv"
	"strings"
	"time"

	"codeberg.org/urutau-ltd/bellbird/pqc"
	"codeberg.org/urutau-ltd/bellbird/proxy"
)

// Config holds all relay configuration.
type Config struct {
	// ListenAddr is the address to accept tunnel connections on, e.g. ":9999".
	ListenAddr string

	// PrivateKey is the relay's hybrid private key (pqc.Sizes.PrivateTotal bytes).
	// Generated by: bellbird keygen --out relay
	PrivateKey []byte

	// AuthToken enables optional client authentication.
	// If empty, no client authentication is required.
	AuthToken string

	// AllowLocalTargets permits relay connections to localhost/link-local/
	// unspecified target addresses. Disabled by default for safer exposure.
	AllowLocalTargets bool
}

// Relay is a bellbird relay server.
type Relay struct {
	cfg Config
}

var (
	errAuthFrameRequired = errors.New("relay: auth required but auth frame missing")
	errAuthTokenInvalid  = errors.New("relay: invalid auth token")
	errLocalTargetDenied = errors.New("relay: local or special target address denied")
)

// New creates a Relay. Call Start to begin accepting connections.
func New(cfg Config) (*Relay, error) {
	if cfg.ListenAddr == "" {
		return nil, fmt.Errorf("relay: ListenAddr is required")
	}
	if len(cfg.PrivateKey) == 0 {
		return nil, fmt.Errorf("relay: PrivateKey is required")
	}
	if len(cfg.PrivateKey) != pqc.Sizes.PrivateTotal {
		return nil, fmt.Errorf("relay: PrivateKey must be %d bytes, got %d", pqc.Sizes.PrivateTotal, len(cfg.PrivateKey))
	}
	return &Relay{cfg: cfg}, nil
}

// Start listens for incoming PQC tunnel connections.
// Each connection is handled in its own goroutine.
// Blocks until ctx is cancelled.
func (r *Relay) Start(ctx context.Context) error {
	ln, err := net.Listen("tcp", r.cfg.ListenAddr)
	if err != nil {
		return fmt.Errorf("relay listen %s: %w", r.cfg.ListenAddr, err)
	}
	defer ln.Close()

	log.Printf("bellbird relay: listening on %s", r.cfg.ListenAddr)

	go func() {
		<-ctx.Done()
		ln.Close()
	}()

	for {
		conn, err := ln.Accept()
		if err != nil {
			select {
			case <-ctx.Done():
				return nil
			default:
				log.Printf("relay: accept error: %v", err)
				continue
			}
		}
		go r.handleConn(conn)
	}
}

// ─── Internal ──────────────────────────────────────────────────────────────

func (r *Relay) handleConn(conn net.Conn) {
	defer conn.Close()

	// PQC handshake: derive session key from client's KEM ciphertext.
	tunnel, err := proxy.NewRelayTunnel(conn, r.cfg.PrivateKey)
	if err != nil {
		log.Printf("relay: PQC handshake: %v", err)
		return
	}

	target, err := r.readConnectTarget(tunnel)
	if err != nil {
		log.Printf("relay: session setup failed: %v", err)
		return
	}
	if err := conn.SetDeadline(time.Time{}); err != nil {
		log.Printf("relay: clear setup deadline failed: %v", err)
		return
	}

	dest, err := r.dialTarget(target)
	if err != nil {
		log.Printf("relay: dial target failed: %v", err)
		return
	}
	defer dest.Close()

	log.Printf("relay: forwarding session")

	errCh := make(chan error, 2)

	// tunnel → dest
	// Read encrypted frames from client, unpad, write raw bytes to destination.
	go func() {
		for {
			pt, data, err := tunnel.ReadFrame()
			if err != nil {
				errCh <- err
				return
			}
			switch pt {
			case proxy.PacketData:
				if _, err := dest.Write(proxy.UnpadData(data)); err != nil {
					errCh <- err
					return
				}
			case proxy.PacketDummy, proxy.PacketPing:
				// Discard — these are traffic-shaping artifacts.
			}
		}
	}()

	// dest → tunnel
	// Read raw bytes from destination, pad to block boundary, send as encrypted frames.
	go func() {
		buf := make([]byte, 32*1024)
		for {
			n, err := dest.Read(buf)
			if n > 0 {
				padded := proxy.PadData(buf[:n], proxy.PadSize(n))
				if werr := tunnel.WriteFrame(proxy.PacketData, padded); werr != nil {
					errCh <- werr
					return
				}
			}
			if err != nil {
				errCh <- err
				return
			}
		}
	}()

	<-errCh
	go func() { <-errCh }() // drain second error to avoid goroutine leak
}

func (r *Relay) readConnectTarget(tunnel *proxy.Tunnel) (string, error) {
	pktType, payload, err := tunnel.ReadFrame()
	if err != nil {
		return "", fmt.Errorf("read first frame: %w", err)
	}

	if r.cfg.AuthToken != "" {
		if err := validateAuthFrame(r.cfg.AuthToken, pktType, payload); err != nil {
			return "", err
		}

		pktType, payload, err = tunnel.ReadFrame()
		if err != nil {
			return "", fmt.Errorf("read connect frame: %w", err)
		}
	} else if pktType == proxy.PacketAuth {
		// Open relay mode: accept an optional auth frame for forward compatibility.
		pktType, payload, err = tunnel.ReadFrame()
		if err != nil {
			return "", fmt.Errorf("read connect frame after auth: %w", err)
		}
	}

	if pktType != proxy.PacketConnect {
		return "", fmt.Errorf("expected PacketConnect (0x04), got 0x%02x", pktType)
	}

	return validateConnectTarget(string(payload), r.cfg.AllowLocalTargets)
}

func validateAuthFrame(expectedToken string, pktType byte, payload []byte) error {
	if expectedToken == "" {
		return nil
	}
	if pktType != proxy.PacketAuth {
		return errAuthFrameRequired
	}
	expectedHash := sha256.Sum256([]byte(expectedToken))
	payloadHash := sha256.Sum256(payload)
	if subtle.ConstantTimeCompare(expectedHash[:], payloadHash[:]) != 1 {
		return errAuthTokenInvalid
	}
	return nil
}

func validateConnectTarget(rawTarget string, allowLocal bool) (string, error) {
	if len(rawTarget) == 0 || len(rawTarget) > 512 {
		return "", fmt.Errorf("invalid connect target length: %d", len(rawTarget))
	}

	host, portStr, err := net.SplitHostPort(rawTarget)
	if err != nil {
		return "", fmt.Errorf("invalid connect target %q: %w", rawTarget, err)
	}

	port, err := strconv.Atoi(portStr)
	if err != nil || port < 1 || port > 65535 {
		return "", fmt.Errorf("invalid connect target port %q", portStr)
	}

	if allowLocal {
		return net.JoinHostPort(host, strconv.Itoa(port)), nil
	}

	if strings.EqualFold(host, "localhost") {
		return "", errLocalTargetDenied
	}

	if ip := net.ParseIP(host); ip != nil && isDeniedTargetIP(ip) {
		return "", errLocalTargetDenied
	}

	return net.JoinHostPort(host, strconv.Itoa(port)), nil
}

func isDeniedTargetIP(ip net.IP) bool {
	return ip.IsLoopback() ||
		ip.IsUnspecified() ||
		ip.IsMulticast() ||
		ip.IsLinkLocalUnicast() ||
		ip.IsLinkLocalMulticast()
}

func firstAllowedIP(ips []net.IP) (net.IP, bool) {
	for _, ip := range ips {
		if !isDeniedTargetIP(ip) {
			return ip, true
		}
	}
	return nil, false
}

func (r *Relay) dialTarget(target string) (net.Conn, error) {
	host, port, err := net.SplitHostPort(target)
	if err != nil {
		return nil, fmt.Errorf("split target host/port %q: %w", target, err)
	}

	dialer := net.Dialer{
		Timeout:   10 * time.Second,
		KeepAlive: 30 * time.Second,
	}

	if r.cfg.AllowLocalTargets {
		return dialer.Dial("tcp", net.JoinHostPort(host, port))
	}

	if strings.EqualFold(host, "localhost") {
		return nil, errLocalTargetDenied
	}

	if ip := net.ParseIP(host); ip != nil {
		if isDeniedTargetIP(ip) {
			return nil, errLocalTargetDenied
		}
		return dialer.Dial("tcp", net.JoinHostPort(ip.String(), port))
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	ips, err := net.DefaultResolver.LookupIP(ctx, "ip", host)
	if err != nil {
		return nil, fmt.Errorf("resolve target host %q: %w", host, err)
	}
	allowedIP, ok := firstAllowedIP(ips)
	if !ok {
		return nil, errLocalTargetDenied
	}
	return dialer.Dial("tcp", net.JoinHostPort(allowedIP.String(), port))
}
